services:
  db:
    image: mysql:8.0
    container_name: bb_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-password
      MYSQL_DATABASE: bb-project
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  server:
    build: ./server
    container_name: bb_server
    restart: always
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: my-password
      DB_NAME: bb-project
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules

  client:
    build: ./client
    container_name: bb_client
    restart: always
    depends_on:
      - server
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules

volumes:
  db_data:
  client_node_modules:
  server_node_modules: